#pragma once

// GENERATED by Tools/als_template/make_als_template.py - do not edit by hand.
//
// Derived from a Live Set saved by Ableton Live 11.3.13, from
// github.com/Ableton/maxdevtools (maxdiff/tests/test_files/Test Project/Test.als),
// Copyright (c) 2024 Ableton AG, MIT License - see
// Tools/als_template/LICENSE-Ableton-maxdevtools.txt.

namespace Engine
{
namespace AlsTemplate
{
    // Number of @Pk@ pool-id placeholders in kAlsMidiTrack.
    constexpr int kPoolIdsPerTrack = 152;
    // First free pool id above everything in kAlsHead/kAlsTail.
    constexpr int kFirstTrackPoolId = 19733;

    constexpr const char* kAlsHead = R"ALS(<?xml version="1.0" encoding="UTF-8"?>
<Ableton MajorVersion="5" MinorVersion="11.0_11300" SchemaChangeCount="3" Creator="Ableton Live 11.3.13" Revision="b376a4ffe2734bb43bb06f3a36871bb868ae2231">
	<LiveSet>
		<NextPointeeId Value="@NEXT_POINTEE_ID@" />
		<OverwriteProtectionNumber Value="2819" />
		<LomId Value="0" />
		<LomIdView Value="0" />
		<Tracks>
)ALS";

    constexpr const char* kAlsMidiTrack = R"ALS(			<MidiTrack Id="@TRACK_ID@">
				<LomId Value="0" />
				<LomIdView Value="0" />
				<IsContentSelectedInDocument Value="false" />
				<PreferredContentViewMode Value="0" />
				<TrackDelay>
					<Value Value="0" />
					<IsValueSampleBased Value="false" />
				</TrackDelay>
				<Name>
					<EffectiveName Value="@NAME@" />
					<UserName Value="@NAME@" />
					<Annotation Value="" />
					<MemorizedFirstClipName Value="" />
				</Name>
				<Color Value="@COLOR@" />
				<AutomationEnvelopes>
					<Envelopes />
				</AutomationEnvelopes>
				<TrackGroupId Value="-1" />
				<TrackUnfolded Value="true" />
				<DevicesListWrapper LomId="0" />
				<ClipSlotsListWrapper LomId="0" />
				<ViewData Value="{}" />
				<TakeLanes>
					<TakeLanes />
					<AreTakeLanesFolded Value="true" />
				</TakeLanes>
				<LinkedTrackGroupId Value="-1" />
				<SavedPlayingSlot Value="-1" />
				<SavedPlayingOffset Value="0" />
				<Freeze Value="false" />
				<VelocityDetail Value="0" />
				<NeedArrangerRefreeze Value="true" />
				<PostProcessFreezeClips Value="0" />
				<DeviceChain>
					<AutomationLanes>
						<AutomationLanes>
							<AutomationLane Id="0">
								<SelectedDevice Value="2" />
								<SelectedEnvelope Value="0" />
								<IsContentSelectedInDocument Value="true" />
								<LaneHeight Value="68" />
							</AutomationLane>
						</AutomationLanes>
						<AreAdditionalAutomationLanesFolded Value="false" />
					</AutomationLanes>
					<ClipEnvelopeChooserViewState>
						<SelectedDevice Value="2" />
						<SelectedEnvelope Value="0" />
						<PreferModulationVisible Value="false" />
					</ClipEnvelopeChooserViewState>
					<AudioInputRouting>
						<Target Value="AudioIn/External/S0" />
						<UpperDisplayString Value="Ext. In" />
						<LowerDisplayString Value="1/2" />
						<MpeSettings>
							<ZoneType Value="0" />
							<FirstNoteChannel Value="1" />
							<LastNoteChannel Value="15" />
						</MpeSettings>
					</AudioInputRouting>
					<MidiInputRouting>
						<Target Value="MidiIn/External.All/-1" />
						<UpperDisplayString Value="Ext: All Ins" />
						<LowerDisplayString Value="" />
						<MpeSettings>
							<ZoneType Value="0" />
							<FirstNoteChannel Value="1" />
							<LastNoteChannel Value="15" />
						</MpeSettings>
					</MidiInputRouting>
					<AudioOutputRouting>
						<Target Value="AudioOut/Master" />
						<UpperDisplayString Value="Master" />
						<LowerDisplayString Value="" />
						<MpeSettings>
							<ZoneType Value="0" />
							<FirstNoteChannel Value="1" />
							<LastNoteChannel Value="15" />
						</MpeSettings>
					</AudioOutputRouting>
					<MidiOutputRouting>
						<Target Value="MidiOut/None" />
						<UpperDisplayString Value="None" />
						<LowerDisplayString Value="" />
						<MpeSettings>
							<ZoneType Value="0" />
							<FirstNoteChannel Value="1" />
							<LastNoteChannel Value="15" />
						</MpeSettings>
					</MidiOutputRouting>
					<Mixer>
						<LomId Value="0" />
						<LomIdView Value="0" />
						<IsExpanded Value="true" />
						<On>
							<LomId Value="0" />
							<Manual Value="true" />
							<AutomationTarget Id="@P0@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<MidiCCOnOffThresholds>
								<Min Value="64" />
								<Max Value="127" />
							</MidiCCOnOffThresholds>
						</On>
						<ModulationSourceCount Value="0" />
						<ParametersListWrapper LomId="0" />
						<Pointee Id="@P1@" />
						<LastSelectedTimeableIndex Value="0" />
						<LastSelectedClipEnvelopeIndex Value="0" />
						<LastPresetRef>
							<Value />
						</LastPresetRef>
						<LockedScripts />
						<IsFolded Value="false" />
						<ShouldShowPresetName Value="false" />
						<UserName Value="" />
						<Annotation Value="" />
						<SourceContext>
							<Value />
						</SourceContext>
						<Sends />
						<Speaker>
							<LomId Value="0" />
							<Manual Value="true" />
							<AutomationTarget Id="@P2@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<MidiCCOnOffThresholds>
								<Min Value="64" />
								<Max Value="127" />
							</MidiCCOnOffThresholds>
						</Speaker>
						<SoloSink Value="false" />
						<PanMode Value="0" />
						<Pan>
							<LomId Value="0" />
							<Manual Value="0" />
							<MidiControllerRange>
								<Min Value="-1" />
								<Max Value="1" />
							</MidiControllerRange>
							<AutomationTarget Id="@P3@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<ModulationTarget Id="@P4@">
								<LockEnvelope Value="0" />
							</ModulationTarget>
						</Pan>
						<SplitStereoPanL>
							<LomId Value="0" />
							<Manual Value="-1" />
							<MidiControllerRange>
								<Min Value="-1" />
								<Max Value="1" />
							</MidiControllerRange>
							<AutomationTarget Id="@P5@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<ModulationTarget Id="@P6@">
								<LockEnvelope Value="0" />
							</ModulationTarget>
						</SplitStereoPanL>
						<SplitStereoPanR>
							<LomId Value="0" />
							<Manual Value="1" />
							<MidiControllerRange>
								<Min Value="-1" />
								<Max Value="1" />
							</MidiControllerRange>
							<AutomationTarget Id="@P7@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<ModulationTarget Id="@P8@">
								<LockEnvelope Value="0" />
							</ModulationTarget>
						</SplitStereoPanR>
						<Volume>
							<LomId Value="0" />
							<Manual Value="1" />
							<MidiControllerRange>
								<Min Value="0.0003162277571" />
								<Max Value="1.99526238" />
							</MidiControllerRange>
							<AutomationTarget Id="@P9@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<ModulationTarget Id="@P10@">
								<LockEnvelope Value="0" />
							</ModulationTarget>
						</Volume>
						<ViewStateSesstionTrackWidth Value="93" />
						<CrossFadeState>
							<LomId Value="0" />
							<Manual Value="1" />
							<AutomationTarget Id="@P11@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
						</CrossFadeState>
						<SendsListWrapper LomId="0" />
					</Mixer>
					<MainSequencer>
						<LomId Value="0" />
						<LomIdView Value="0" />
						<IsExpanded Value="true" />
						<On>
							<LomId Value="0" />
							<Manual Value="true" />
							<AutomationTarget Id="@P12@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<MidiCCOnOffThresholds>
								<Min Value="64" />
								<Max Value="127" />
							</MidiCCOnOffThresholds>
						</On>
						<ModulationSourceCount Value="0" />
						<ParametersListWrapper LomId="0" />
						<Pointee Id="@P13@" />
						<LastSelectedTimeableIndex Value="0" />
						<LastSelectedClipEnvelopeIndex Value="0" />
						<LastPresetRef>
							<Value />
						</LastPresetRef>
						<LockedScripts />
						<IsFolded Value="false" />
						<ShouldShowPresetName Value="false" />
						<UserName Value="" />
						<Annotation Value="" />
						<SourceContext>
							<Value />
						</SourceContext>
						<ClipSlotList>
							<ClipSlot Id="0">
								<LomId Value="0" />
								<ClipSlot>
									<Value />
								</ClipSlot>
								<HasStop Value="true" />
								<NeedRefreeze Value="true" />
							</ClipSlot>
							<ClipSlot Id="1">
								<LomId Value="0" />
								<ClipSlot>
									<Value />
								</ClipSlot>
								<HasStop Value="true" />
								<NeedRefreeze Value="true" />
							</ClipSlot>
						</ClipSlotList>
						<MonitoringEnum Value="1" />
						<ClipTimeable>
							<ArrangerAutomation>
								@ARRANGEMENT_CLIPS@
								<AutomationTransformViewState>
									<IsTransformPending Value="false" />
									<TimeAndValueTransforms />
								</AutomationTransformViewState>
							</ArrangerAutomation>
						</ClipTimeable>
						<Recorder>
							<IsArmed Value="false" />
							<TakeCounter Value="0" />
						</Recorder>
						<MidiControllers>
							<ControllerTargets.0 Id="@P14@">
								<LockEnvelope Value="0" />
							</ControllerTargets.0>
							<ControllerTargets.1 Id="@P15@">
								<LockEnvelope Value="1" />
							</ControllerTargets.1>
							<ControllerTargets.2 Id="@P16@">
								<LockEnvelope Value="0" />
							</ControllerTargets.2>
							<ControllerTargets.3 Id="@P17@">
								<LockEnvelope Value="0" />
							</ControllerTargets.3>
							<ControllerTargets.4 Id="@P18@">
								<LockEnvelope Value="0" />
							</ControllerTargets.4>
							<ControllerTargets.5 Id="@P19@">
								<LockEnvelope Value="0" />
							</ControllerTargets.5>
							<ControllerTargets.6 Id="@P20@">
								<LockEnvelope Value="0" />
							</ControllerTargets.6>
							<ControllerTargets.7 Id="@P21@">
								<LockEnvelope Value="0" />
							</ControllerTargets.7>
							<ControllerTargets.8 Id="@P22@">
								<LockEnvelope Value="0" />
							</ControllerTargets.8>
							<ControllerTargets.9 Id="@P23@">
								<LockEnvelope Value="0" />
							</ControllerTargets.9>
							<ControllerTargets.10 Id="@P24@">
								<LockEnvelope Value="0" />
							</ControllerTargets.10>
							<ControllerTargets.11 Id="@P25@">
								<LockEnvelope Value="1" />
							</ControllerTargets.11>
							<ControllerTargets.12 Id="@P26@">
								<LockEnvelope Value="0" />
							</ControllerTargets.12>
							<ControllerTargets.13 Id="@P27@">
								<LockEnvelope Value="0" />
							</ControllerTargets.13>
							<ControllerTargets.14 Id="@P28@">
								<LockEnvelope Value="0" />
							</ControllerTargets.14>
							<ControllerTargets.15 Id="@P29@">
								<LockEnvelope Value="0" />
							</ControllerTargets.15>
							<ControllerTargets.16 Id="@P30@">
								<LockEnvelope Value="0" />
							</ControllerTargets.16>
							<ControllerTargets.17 Id="@P31@">
								<LockEnvelope Value="0" />
							</ControllerTargets.17>
							<ControllerTargets.18 Id="@P32@">
								<LockEnvelope Value="0" />
							</ControllerTargets.18>
							<ControllerTargets.19 Id="@P33@">
								<LockEnvelope Value="0" />
							</ControllerTargets.19>
							<ControllerTargets.20 Id="@P34@">
								<LockEnvelope Value="0" />
							</ControllerTargets.20>
							<ControllerTargets.21 Id="@P35@">
								<LockEnvelope Value="0" />
							</ControllerTargets.21>
							<ControllerTargets.22 Id="@P36@">
								<LockEnvelope Value="0" />
							</ControllerTargets.22>
							<ControllerTargets.23 Id="@P37@">
								<LockEnvelope Value="0" />
							</ControllerTargets.23>
							<ControllerTargets.24 Id="@P38@">
								<LockEnvelope Value="0" />
							</ControllerTargets.24>
							<ControllerTargets.25 Id="@P39@">
								<LockEnvelope Value="0" />
							</ControllerTargets.25>
							<ControllerTargets.26 Id="@P40@">
								<LockEnvelope Value="0" />
							</ControllerTargets.26>
							<ControllerTargets.27 Id="@P41@">
								<LockEnvelope Value="0" />
							</ControllerTargets.27>
							<ControllerTargets.28 Id="@P42@">
								<LockEnvelope Value="0" />
							</ControllerTargets.28>
							<ControllerTargets.29 Id="@P43@">
								<LockEnvelope Value="0" />
							</ControllerTargets.29>
							<ControllerTargets.30 Id="@P44@">
								<LockEnvelope Value="0" />
							</ControllerTargets.30>
							<ControllerTargets.31 Id="@P45@">
								<LockEnvelope Value="0" />
							</ControllerTargets.31>
							<ControllerTargets.32 Id="@P46@">
								<LockEnvelope Value="0" />
							</ControllerTargets.32>
							<ControllerTargets.33 Id="@P47@">
								<LockEnvelope Value="0" />
							</ControllerTargets.33>
							<ControllerTargets.34 Id="@P48@">
								<LockEnvelope Value="0" />
							</ControllerTargets.34>
							<ControllerTargets.35 Id="@P49@">
								<LockEnvelope Value="0" />
							</ControllerTargets.35>
							<ControllerTargets.36 Id="@P50@">
								<LockEnvelope Value="0" />
							</ControllerTargets.36>
							<ControllerTargets.37 Id="@P51@">
								<LockEnvelope Value="0" />
							</ControllerTargets.37>
							<ControllerTargets.38 Id="@P52@">
								<LockEnvelope Value="0" />
							</ControllerTargets.38>
							<ControllerTargets.39 Id="@P53@">
								<LockEnvelope Value="0" />
							</ControllerTargets.39>
							<ControllerTargets.40 Id="@P54@">
								<LockEnvelope Value="0" />
							</ControllerTargets.40>
							<ControllerTargets.41 Id="@P55@">
								<LockEnvelope Value="0" />
							</ControllerTargets.41>
							<ControllerTargets.42 Id="@P56@">
								<LockEnvelope Value="0" />
							</ControllerTargets.42>
							<ControllerTargets.43 Id="@P57@">
								<LockEnvelope Value="0" />
							</ControllerTargets.43>
							<ControllerTargets.44 Id="@P58@">
								<LockEnvelope Value="0" />
							</ControllerTargets.44>
							<ControllerTargets.45 Id="@P59@">
								<LockEnvelope Value="0" />
							</ControllerTargets.45>
							<ControllerTargets.46 Id="@P60@">
								<LockEnvelope Value="0" />
							</ControllerTargets.46>
							<ControllerTargets.47 Id="@P61@">
								<LockEnvelope Value="0" />
							</ControllerTargets.47>
							<ControllerTargets.48 Id="@P62@">
								<LockEnvelope Value="0" />
							</ControllerTargets.48>
							<ControllerTargets.49 Id="@P63@">
								<LockEnvelope Value="0" />
							</ControllerTargets.49>
							<ControllerTargets.50 Id="@P64@">
								<LockEnvelope Value="0" />
							</ControllerTargets.50>
							<ControllerTargets.51 Id="@P65@">
								<LockEnvelope Value="0" />
							</ControllerTargets.51>
							<ControllerTargets.52 Id="@P66@">
								<LockEnvelope Value="0" />
							</ControllerTargets.52>
							<ControllerTargets.53 Id="@P67@">
								<LockEnvelope Value="0" />
							</ControllerTargets.53>
							<ControllerTargets.54 Id="@P68@">
								<LockEnvelope Value="0" />
							</ControllerTargets.54>
							<ControllerTargets.55 Id="@P69@">
								<LockEnvelope Value="0" />
							</ControllerTargets.55>
							<ControllerTargets.56 Id="@P70@">
								<LockEnvelope Value="0" />
							</ControllerTargets.56>
							<ControllerTargets.57 Id="@P71@">
								<LockEnvelope Value="0" />
							</ControllerTargets.57>
							<ControllerTargets.58 Id="@P72@">
								<LockEnvelope Value="0" />
							</ControllerTargets.58>
							<ControllerTargets.59 Id="@P73@">
								<LockEnvelope Value="0" />
							</ControllerTargets.59>
							<ControllerTargets.60 Id="@P74@">
								<LockEnvelope Value="0" />
							</ControllerTargets.60>
							<ControllerTargets.61 Id="@P75@">
								<LockEnvelope Value="0" />
							</ControllerTargets.61>
							<ControllerTargets.62 Id="@P76@">
								<LockEnvelope Value="0" />
							</ControllerTargets.62>
							<ControllerTargets.63 Id="@P77@">
								<LockEnvelope Value="0" />
							</ControllerTargets.63>
							<ControllerTargets.64 Id="@P78@">
								<LockEnvelope Value="0" />
							</ControllerTargets.64>
							<ControllerTargets.65 Id="@P79@">
								<LockEnvelope Value="0" />
							</ControllerTargets.65>
							<ControllerTargets.66 Id="@P80@">
								<LockEnvelope Value="1" />
							</ControllerTargets.66>
							<ControllerTargets.67 Id="@P81@">
								<LockEnvelope Value="0" />
							</ControllerTargets.67>
							<ControllerTargets.68 Id="@P82@">
								<LockEnvelope Value="0" />
							</ControllerTargets.68>
							<ControllerTargets.69 Id="@P83@">
								<LockEnvelope Value="0" />
							</ControllerTargets.69>
							<ControllerTargets.70 Id="@P84@">
								<LockEnvelope Value="0" />
							</ControllerTargets.70>
							<ControllerTargets.71 Id="@P85@">
								<LockEnvelope Value="0" />
							</ControllerTargets.71>
							<ControllerTargets.72 Id="@P86@">
								<LockEnvelope Value="0" />
							</ControllerTargets.72>
							<ControllerTargets.73 Id="@P87@">
								<LockEnvelope Value="0" />
							</ControllerTargets.73>
							<ControllerTargets.74 Id="@P88@">
								<LockEnvelope Value="0" />
							</ControllerTargets.74>
							<ControllerTargets.75 Id="@P89@">
								<LockEnvelope Value="0" />
							</ControllerTargets.75>
							<ControllerTargets.76 Id="@P90@">
								<LockEnvelope Value="0" />
							</ControllerTargets.76>
							<ControllerTargets.77 Id="@P91@">
								<LockEnvelope Value="0" />
							</ControllerTargets.77>
							<ControllerTargets.78 Id="@P92@">
								<LockEnvelope Value="0" />
							</ControllerTargets.78>
							<ControllerTargets.79 Id="@P93@">
								<LockEnvelope Value="0" />
							</ControllerTargets.79>
							<ControllerTargets.80 Id="@P94@">
								<LockEnvelope Value="0" />
							</ControllerTargets.80>
							<ControllerTargets.81 Id="@P95@">
								<LockEnvelope Value="0" />
							</ControllerTargets.81>
							<ControllerTargets.82 Id="@P96@">
								<LockEnvelope Value="0" />
							</ControllerTargets.82>
							<ControllerTargets.83 Id="@P97@">
								<LockEnvelope Value="0" />
							</ControllerTargets.83>
							<ControllerTargets.84 Id="@P98@">
								<LockEnvelope Value="0" />
							</ControllerTargets.84>
							<ControllerTargets.85 Id="@P99@">
								<LockEnvelope Value="0" />
							</ControllerTargets.85>
							<ControllerTargets.86 Id="@P100@">
								<LockEnvelope Value="0" />
							</ControllerTargets.86>
							<ControllerTargets.87 Id="@P101@">
								<LockEnvelope Value="0" />
							</ControllerTargets.87>
							<ControllerTargets.88 Id="@P102@">
								<LockEnvelope Value="0" />
							</ControllerTargets.88>
							<ControllerTargets.89 Id="@P103@">
								<LockEnvelope Value="0" />
							</ControllerTargets.89>
							<ControllerTargets.90 Id="@P104@">
								<LockEnvelope Value="0" />
							</ControllerTargets.90>
							<ControllerTargets.91 Id="@P105@">
								<LockEnvelope Value="0" />
							</ControllerTargets.91>
							<ControllerTargets.92 Id="@P106@">
								<LockEnvelope Value="0" />
							</ControllerTargets.92>
							<ControllerTargets.93 Id="@P107@">
								<LockEnvelope Value="0" />
							</ControllerTargets.93>
							<ControllerTargets.94 Id="@P108@">
								<LockEnvelope Value="0" />
							</ControllerTargets.94>
							<ControllerTargets.95 Id="@P109@">
								<LockEnvelope Value="0" />
							</ControllerTargets.95>
							<ControllerTargets.96 Id="@P110@">
								<LockEnvelope Value="0" />
							</ControllerTargets.96>
							<ControllerTargets.97 Id="@P111@">
								<LockEnvelope Value="0" />
							</ControllerTargets.97>
							<ControllerTargets.98 Id="@P112@">
								<LockEnvelope Value="0" />
							</ControllerTargets.98>
							<ControllerTargets.99 Id="@P113@">
								<LockEnvelope Value="0" />
							</ControllerTargets.99>
							<ControllerTargets.100 Id="@P114@">
								<LockEnvelope Value="0" />
							</ControllerTargets.100>
							<ControllerTargets.101 Id="@P115@">
								<LockEnvelope Value="0" />
							</ControllerTargets.101>
							<ControllerTargets.102 Id="@P116@">
								<LockEnvelope Value="0" />
							</ControllerTargets.102>
							<ControllerTargets.103 Id="@P117@">
								<LockEnvelope Value="0" />
							</ControllerTargets.103>
							<ControllerTargets.104 Id="@P118@">
								<LockEnvelope Value="0" />
							</ControllerTargets.104>
							<ControllerTargets.105 Id="@P119@">
								<LockEnvelope Value="0" />
							</ControllerTargets.105>
							<ControllerTargets.106 Id="@P120@">
								<LockEnvelope Value="0" />
							</ControllerTargets.106>
							<ControllerTargets.107 Id="@P121@">
								<LockEnvelope Value="0" />
							</ControllerTargets.107>
							<ControllerTargets.108 Id="@P122@">
								<LockEnvelope Value="0" />
							</ControllerTargets.108>
							<ControllerTargets.109 Id="@P123@">
								<LockEnvelope Value="0" />
							</ControllerTargets.109>
							<ControllerTargets.110 Id="@P124@">
								<LockEnvelope Value="0" />
							</ControllerTargets.110>
							<ControllerTargets.111 Id="@P125@">
								<LockEnvelope Value="0" />
							</ControllerTargets.111>
							<ControllerTargets.112 Id="@P126@">
								<LockEnvelope Value="0" />
							</ControllerTargets.112>
							<ControllerTargets.113 Id="@P127@">
								<LockEnvelope Value="0" />
							</ControllerTargets.113>
							<ControllerTargets.114 Id="@P128@">
								<LockEnvelope Value="0" />
							</ControllerTargets.114>
							<ControllerTargets.115 Id="@P129@">
								<LockEnvelope Value="0" />
							</ControllerTargets.115>
							<ControllerTargets.116 Id="@P130@">
								<LockEnvelope Value="0" />
							</ControllerTargets.116>
							<ControllerTargets.117 Id="@P131@">
								<LockEnvelope Value="0" />
							</ControllerTargets.117>
							<ControllerTargets.118 Id="@P132@">
								<LockEnvelope Value="0" />
							</ControllerTargets.118>
							<ControllerTargets.119 Id="@P133@">
								<LockEnvelope Value="0" />
							</ControllerTargets.119>
							<ControllerTargets.120 Id="@P134@">
								<LockEnvelope Value="0" />
							</ControllerTargets.120>
							<ControllerTargets.121 Id="@P135@">
								<LockEnvelope Value="0" />
							</ControllerTargets.121>
							<ControllerTargets.122 Id="@P136@">
								<LockEnvelope Value="0" />
							</ControllerTargets.122>
							<ControllerTargets.123 Id="@P137@">
								<LockEnvelope Value="0" />
							</ControllerTargets.123>
							<ControllerTargets.124 Id="@P138@">
								<LockEnvelope Value="0" />
							</ControllerTargets.124>
							<ControllerTargets.125 Id="@P139@">
								<LockEnvelope Value="0" />
							</ControllerTargets.125>
							<ControllerTargets.126 Id="@P140@">
								<LockEnvelope Value="0" />
							</ControllerTargets.126>
							<ControllerTargets.127 Id="@P141@">
								<LockEnvelope Value="0" />
							</ControllerTargets.127>
							<ControllerTargets.128 Id="@P142@">
								<LockEnvelope Value="0" />
							</ControllerTargets.128>
							<ControllerTargets.129 Id="@P143@">
								<LockEnvelope Value="0" />
							</ControllerTargets.129>
							<ControllerTargets.130 Id="@P144@">
								<LockEnvelope Value="0" />
							</ControllerTargets.130>
						</MidiControllers>
					</MainSequencer>
					<FreezeSequencer>
						<LomId Value="0" />
						<LomIdView Value="0" />
						<IsExpanded Value="true" />
						<On>
							<LomId Value="0" />
							<Manual Value="true" />
							<AutomationTarget Id="@P145@">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<MidiCCOnOffThresholds>
								<Min Value="64" />
								<Max Value="127" />
							</MidiCCOnOffThresholds>
						</On>
						<ModulationSourceCount Value="0" />
						<ParametersListWrapper LomId="0" />
						<Pointee Id="@P146@" />
						<LastSelectedTimeableIndex Value="0" />
						<LastSelectedClipEnvelopeIndex Value="0" />
						<LastPresetRef>
							<Value />
						</LastPresetRef>
						<LockedScripts />
						<IsFolded Value="false" />
						<ShouldShowPresetName Value="false" />
						<UserName Value="" />
						<Annotation Value="" />
						<SourceContext>
							<Value />
						</SourceContext>
						<ClipSlotList>
							<ClipSlot Id="0">
								<LomId Value="0" />
								<ClipSlot>
									<Value />
								</ClipSlot>
								<HasStop Value="true" />
								<NeedRefreeze Value="true" />
							</ClipSlot>
							<ClipSlot Id="1">
								<LomId Value="0" />
								<ClipSlot>
									<Value />
								</ClipSlot>
								<HasStop Value="true" />
								<NeedRefreeze Value="true" />
							</ClipSlot>
						</ClipSlotList>
						<MonitoringEnum Value="1" />
						<Sample>
							<ArrangerAutomation>
								<Events />
								<AutomationTransformViewState>
									<IsTransformPending Value="false" />
									<TimeAndValueTransforms />
								</AutomationTransformViewState>
							</ArrangerAutomation>
						</Sample>
						<VolumeModulationTarget Id="@P147@">
							<LockEnvelope Value="0" />
						</VolumeModulationTarget>
						<TranspositionModulationTarget Id="@P148@">
							<LockEnvelope Value="0" />
						</TranspositionModulationTarget>
						<GrainSizeModulationTarget Id="@P149@">
							<LockEnvelope Value="0" />
						</GrainSizeModulationTarget>
						<FluxModulationTarget Id="@P150@">
							<LockEnvelope Value="0" />
						</FluxModulationTarget>
						<SampleOffsetModulationTarget Id="@P151@">
							<LockEnvelope Value="0" />
						</SampleOffsetModulationTarget>
						<PitchViewScrollPosition Value="-1073741824" />
						<SampleOffsetModulationScrollPosition Value="-1073741824" />
						<Recorder>
							<IsArmed Value="false" />
							<TakeCounter Value="1" />
						</Recorder>
					</FreezeSequencer>
					<DeviceChain>
						<Devices />
						<SignalModulations />
					</DeviceChain>
				</DeviceChain>
				<ReWireSlaveMidiTargetId Value="0" />
				<PitchbendRange Value="96" />
			</MidiTrack>
)ALS";

    constexpr const char* kAlsTail = R"ALS(		</Tracks>
		<MasterTrack>
			<LomId Value="0" />
			<LomIdView Value="0" />
			<IsContentSelectedInDocument Value="false" />
			<PreferredContentViewMode Value="0" />
			<TrackDelay>
				<Value Value="0" />
				<IsValueSampleBased Value="false" />
			</TrackDelay>
			<Name>
				<EffectiveName Value="Master" />
				<UserName Value="" />
				<Annotation Value="" />
				<MemorizedFirstClipName Value="" />
			</Name>
			<Color Value="16" />
			<AutomationEnvelopes>
				<Envelopes>
					<AutomationEnvelope Id="0">
						<EnvelopeTarget>
							<PointeeId Value="10" />
						</EnvelopeTarget>
						<Automation>
							<Events>
								<EnumEvent Id="0" Time="-63072000" Value="201" />
							</Events>
							<AutomationTransformViewState>
								<IsTransformPending Value="false" />
								<TimeAndValueTransforms />
							</AutomationTransformViewState>
						</Automation>
					</AutomationEnvelope>
					<AutomationEnvelope Id="1">
						<EnvelopeTarget>
							<PointeeId Value="8" />
						</EnvelopeTarget>
						<Automation>
							<Events>
								<FloatEvent Id="2" Time="-63072000" Value="@TEMPO@" />
							</Events>
							<AutomationTransformViewState>
								<IsTransformPending Value="false" />
								<TimeAndValueTransforms />
							</AutomationTransformViewState>
						</Automation>
					</AutomationEnvelope>
				</Envelopes>
			</AutomationEnvelopes>
			<TrackGroupId Value="-1" />
			<TrackUnfolded Value="false" />
			<DevicesListWrapper LomId="0" />
			<ClipSlotsListWrapper LomId="0" />
			<ViewData Value="{}" />
			<TakeLanes>
				<TakeLanes />
				<AreTakeLanesFolded Value="true" />
			</TakeLanes>
			<LinkedTrackGroupId Value="-1" />
			<DeviceChain>
				<AutomationLanes>
					<AutomationLanes>
						<AutomationLane Id="0">
							<SelectedDevice Value="1" />
							<SelectedEnvelope Value="3" />
							<IsContentSelectedInDocument Value="false" />
							<LaneHeight Value="85" />
						</AutomationLane>
					</AutomationLanes>
					<AreAdditionalAutomationLanesFolded Value="false" />
				</AutomationLanes>
				<ClipEnvelopeChooserViewState>
					<SelectedDevice Value="0" />
					<SelectedEnvelope Value="0" />
					<PreferModulationVisible Value="false" />
				</ClipEnvelopeChooserViewState>
				<AudioInputRouting>
					<Target Value="AudioIn/External/S0" />
					<UpperDisplayString Value="Ext. In" />
					<LowerDisplayString Value="1/2" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</AudioInputRouting>
				<MidiInputRouting>
					<Target Value="MidiIn/External.All/-1" />
					<UpperDisplayString Value="Ext: All Ins" />
					<LowerDisplayString Value="" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</MidiInputRouting>
				<AudioOutputRouting>
					<Target Value="AudioOut/External/S0" />
					<UpperDisplayString Value="Ext. Out" />
					<LowerDisplayString Value="1/2" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</AudioOutputRouting>
				<MidiOutputRouting>
					<Target Value="MidiOut/None" />
					<UpperDisplayString Value="None" />
					<LowerDisplayString Value="" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</MidiOutputRouting>
				<Mixer>
					<LomId Value="0" />
					<LomIdView Value="0" />
					<IsExpanded Value="true" />
					<On>
						<LomId Value="0" />
						<Manual Value="true" />
						<AutomationTarget Id="1">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<MidiCCOnOffThresholds>
							<Min Value="64" />
							<Max Value="127" />
						</MidiCCOnOffThresholds>
					</On>
					<ModulationSourceCount Value="0" />
					<ParametersListWrapper LomId="0" />
					<Pointee Id="19730" />
					<LastSelectedTimeableIndex Value="3" />
					<LastSelectedClipEnvelopeIndex Value="0" />
					<LastPresetRef>
						<Value />
					</LastPresetRef>
					<LockedScripts />
					<IsFolded Value="false" />
					<ShouldShowPresetName Value="false" />
					<UserName Value="" />
					<Annotation Value="" />
					<SourceContext>
						<Value />
					</SourceContext>
					<Sends />
					<Speaker>
						<LomId Value="0" />
						<Manual Value="true" />
						<AutomationTarget Id="2">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<MidiCCOnOffThresholds>
							<Min Value="64" />
							<Max Value="127" />
						</MidiCCOnOffThresholds>
					</Speaker>
					<SoloSink Value="false" />
					<PanMode Value="0" />
					<Pan>
						<LomId Value="0" />
						<Manual Value="0" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="3">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="4">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</Pan>
					<SplitStereoPanL>
						<LomId Value="0" />
						<Manual Value="-1" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="16175">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="16176">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</SplitStereoPanL>
					<SplitStereoPanR>
						<LomId Value="0" />
						<Manual Value="1" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="16177">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="16178">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</SplitStereoPanR>
					<Volume>
						<LomId Value="0" />
						<Manual Value="1" />
						<MidiControllerRange>
							<Min Value="0.0003162277571" />
							<Max Value="1.99526238" />
						</MidiControllerRange>
						<AutomationTarget Id="5">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="6">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</Volume>
					<ViewStateSesstionTrackWidth Value="93" />
					<CrossFadeState>
						<LomId Value="0" />
						<Manual Value="1" />
						<AutomationTarget Id="7">
							<LockEnvelope Value="0" />
						</AutomationTarget>
					</CrossFadeState>
					<SendsListWrapper LomId="0" />
					<Tempo>
						<LomId Value="0" />
						<Manual Value="@TEMPO@" />
						<MidiControllerRange>
							<Min Value="60" />
							<Max Value="200" />
						</MidiControllerRange>
						<AutomationTarget Id="8">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="9">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</Tempo>
					<TimeSignature>
						<LomId Value="0" />
						<Manual Value="201" />
						<AutomationTarget Id="10">
							<LockEnvelope Value="0" />
						</AutomationTarget>
					</TimeSignature>
					<GlobalGrooveAmount>
						<LomId Value="0" />
						<Manual Value="100" />
						<MidiControllerRange>
							<Min Value="0" />
							<Max Value="131.25" />
						</MidiControllerRange>
						<AutomationTarget Id="11">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="12">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</GlobalGrooveAmount>
					<CrossFade>
						<LomId Value="0" />
						<Manual Value="0" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="13">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="14">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</CrossFade>
					<TempoAutomationViewBottom Value="60" />
					<TempoAutomationViewTop Value="200" />
				</Mixer>
				<FreezeSequencer>
					<AudioSequencer Id="0">
						<LomId Value="0" />
						<LomIdView Value="0" />
						<IsExpanded Value="true" />
						<On>
							<LomId Value="0" />
							<Manual Value="true" />
							<AutomationTarget Id="15">
								<LockEnvelope Value="0" />
							</AutomationTarget>
							<MidiCCOnOffThresholds>
								<Min Value="64" />
								<Max Value="127" />
							</MidiCCOnOffThresholds>
						</On>
						<ModulationSourceCount Value="0" />
						<ParametersListWrapper LomId="0" />
						<Pointee Id="19731" />
						<LastSelectedTimeableIndex Value="0" />
						<LastSelectedClipEnvelopeIndex Value="0" />
						<LastPresetRef>
							<Value />
						</LastPresetRef>
						<LockedScripts />
						<IsFolded Value="false" />
						<ShouldShowPresetName Value="false" />
						<UserName Value="" />
						<Annotation Value="" />
						<SourceContext>
							<Value />
						</SourceContext>
						<ClipSlotList />
						<MonitoringEnum Value="1" />
						<Sample>
							<ArrangerAutomation>
								<Events />
								<AutomationTransformViewState>
									<IsTransformPending Value="false" />
									<TimeAndValueTransforms />
								</AutomationTransformViewState>
							</ArrangerAutomation>
						</Sample>
						<VolumeModulationTarget Id="16">
							<LockEnvelope Value="0" />
						</VolumeModulationTarget>
						<TranspositionModulationTarget Id="17">
							<LockEnvelope Value="0" />
						</TranspositionModulationTarget>
						<GrainSizeModulationTarget Id="18">
							<LockEnvelope Value="0" />
						</GrainSizeModulationTarget>
						<FluxModulationTarget Id="19">
							<LockEnvelope Value="0" />
						</FluxModulationTarget>
						<SampleOffsetModulationTarget Id="20">
							<LockEnvelope Value="0" />
						</SampleOffsetModulationTarget>
						<PitchViewScrollPosition Value="-1073741824" />
						<SampleOffsetModulationScrollPosition Value="-1073741824" />
						<Recorder>
							<IsArmed Value="false" />
							<TakeCounter Value="1" />
						</Recorder>
					</AudioSequencer>
				</FreezeSequencer>
				<DeviceChain>
					<Devices />
					<SignalModulations />
				</DeviceChain>
			</DeviceChain>
		</MasterTrack>
		<PreHearTrack>
			<LomId Value="0" />
			<LomIdView Value="0" />
			<IsContentSelectedInDocument Value="false" />
			<PreferredContentViewMode Value="0" />
			<TrackDelay>
				<Value Value="0" />
				<IsValueSampleBased Value="false" />
			</TrackDelay>
			<Name>
				<EffectiveName Value="Master" />
				<UserName Value="" />
				<Annotation Value="" />
				<MemorizedFirstClipName Value="" />
			</Name>
			<Color Value="-1" />
			<AutomationEnvelopes>
				<Envelopes />
			</AutomationEnvelopes>
			<TrackGroupId Value="-1" />
			<TrackUnfolded Value="false" />
			<DevicesListWrapper LomId="0" />
			<ClipSlotsListWrapper LomId="0" />
			<ViewData Value="{}" />
			<TakeLanes>
				<TakeLanes />
				<AreTakeLanesFolded Value="true" />
			</TakeLanes>
			<LinkedTrackGroupId Value="-1" />
			<DeviceChain>
				<AutomationLanes>
					<AutomationLanes>
						<AutomationLane Id="0">
							<SelectedDevice Value="0" />
							<SelectedEnvelope Value="0" />
							<IsContentSelectedInDocument Value="false" />
							<LaneHeight Value="85" />
						</AutomationLane>
					</AutomationLanes>
					<AreAdditionalAutomationLanesFolded Value="false" />
				</AutomationLanes>
				<ClipEnvelopeChooserViewState>
					<SelectedDevice Value="0" />
					<SelectedEnvelope Value="0" />
					<PreferModulationVisible Value="false" />
				</ClipEnvelopeChooserViewState>
				<AudioInputRouting>
					<Target Value="AudioIn/External/S0" />
					<UpperDisplayString Value="Ext. In" />
					<LowerDisplayString Value="1/2" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</AudioInputRouting>
				<MidiInputRouting>
					<Target Value="MidiIn/External.All/-1" />
					<UpperDisplayString Value="Ext: All Ins" />
					<LowerDisplayString Value="" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</MidiInputRouting>
				<AudioOutputRouting>
					<Target Value="AudioOut/External/S0" />
					<UpperDisplayString Value="Ext. Out" />
					<LowerDisplayString Value="1/2" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</AudioOutputRouting>
				<MidiOutputRouting>
					<Target Value="MidiOut/None" />
					<UpperDisplayString Value="None" />
					<LowerDisplayString Value="" />
					<MpeSettings>
						<ZoneType Value="0" />
						<FirstNoteChannel Value="1" />
						<LastNoteChannel Value="15" />
					</MpeSettings>
				</MidiOutputRouting>
				<Mixer>
					<LomId Value="0" />
					<LomIdView Value="0" />
					<IsExpanded Value="true" />
					<On>
						<LomId Value="0" />
						<Manual Value="true" />
						<AutomationTarget Id="21">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<MidiCCOnOffThresholds>
							<Min Value="64" />
							<Max Value="127" />
						</MidiCCOnOffThresholds>
					</On>
					<ModulationSourceCount Value="0" />
					<ParametersListWrapper LomId="0" />
					<Pointee Id="19732" />
					<LastSelectedTimeableIndex Value="0" />
					<LastSelectedClipEnvelopeIndex Value="0" />
					<LastPresetRef>
						<Value />
					</LastPresetRef>
					<LockedScripts />
					<IsFolded Value="false" />
					<ShouldShowPresetName Value="false" />
					<UserName Value="" />
					<Annotation Value="" />
					<SourceContext>
						<Value />
					</SourceContext>
					<Sends />
					<Speaker>
						<LomId Value="0" />
						<Manual Value="true" />
						<AutomationTarget Id="22">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<MidiCCOnOffThresholds>
							<Min Value="64" />
							<Max Value="127" />
						</MidiCCOnOffThresholds>
					</Speaker>
					<SoloSink Value="false" />
					<PanMode Value="0" />
					<Pan>
						<LomId Value="0" />
						<Manual Value="0" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="23">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="24">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</Pan>
					<SplitStereoPanL>
						<LomId Value="0" />
						<Manual Value="-1" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="16179">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="16180">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</SplitStereoPanL>
					<SplitStereoPanR>
						<LomId Value="0" />
						<Manual Value="1" />
						<MidiControllerRange>
							<Min Value="-1" />
							<Max Value="1" />
						</MidiControllerRange>
						<AutomationTarget Id="16181">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="16182">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</SplitStereoPanR>
					<Volume>
						<LomId Value="0" />
						<Manual Value="1" />
						<MidiControllerRange>
							<Min Value="0.0003162277571" />
							<Max Value="1.99526238" />
						</MidiControllerRange>
						<AutomationTarget Id="25">
							<LockEnvelope Value="0" />
						</AutomationTarget>
						<ModulationTarget Id="26">
							<LockEnvelope Value="0" />
						</ModulationTarget>
					</Volume>
					<ViewStateSesstionTrackWidth Value="74" />
					<CrossFadeState>
						<LomId Value="0" />
						<Manual Value="1" />
						<AutomationTarget Id="27">
							<LockEnvelope Value="0" />
						</AutomationTarget>
					</CrossFadeState>
					<SendsListWrapper LomId="0" />
				</Mixer>
				<DeviceChain>
					<Devices />
					<SignalModulations />
				</DeviceChain>
			</DeviceChain>
		</PreHearTrack>
		<SendsPre />
		<Scenes>
			<Scene Id="0">
				<FollowAction>
					<FollowTime Value="4" />
					<IsLinked Value="true" />
					<LoopIterations Value="1" />
					<FollowActionA Value="4" />
					<FollowActionB Value="0" />
					<FollowChanceA Value="100" />
					<FollowChanceB Value="0" />
					<JumpIndexA Value="0" />
					<JumpIndexB Value="0" />
					<FollowActionEnabled Value="false" />
				</FollowAction>
				<Name Value="" />
				<Annotation Value="" />
				<Color Value="-1" />
				<Tempo Value="120" />
				<IsTempoEnabled Value="false" />
				<TimeSignatureId Value="201" />
				<IsTimeSignatureEnabled Value="false" />
				<LomId Value="0" />
				<ClipSlotsListWrapper LomId="0" />
			</Scene>
			<Scene Id="1">
				<FollowAction>
					<FollowTime Value="4" />
					<IsLinked Value="true" />
					<LoopIterations Value="1" />
					<FollowActionA Value="4" />
					<FollowActionB Value="0" />
					<FollowChanceA Value="100" />
					<FollowChanceB Value="0" />
					<JumpIndexA Value="0" />
					<JumpIndexB Value="0" />
					<FollowActionEnabled Value="false" />
				</FollowAction>
				<Name Value="" />
				<Annotation Value="" />
				<Color Value="-1" />
				<Tempo Value="120" />
				<IsTempoEnabled Value="false" />
				<TimeSignatureId Value="201" />
				<IsTimeSignatureEnabled Value="false" />
				<LomId Value="0" />
				<ClipSlotsListWrapper LomId="0" />
			</Scene>
		</Scenes>
		<Transport>
			<PhaseNudgeTempo Value="10" />
			<LoopOn Value="false" />
			<LoopStart Value="8" />
			<LoopLength Value="16" />
			<LoopIsSongStart Value="false" />
			<CurrentTime Value="0" />
			<PunchIn Value="false" />
			<PunchOut Value="false" />
			<MetronomeTickDuration Value="0" />
			<DrawMode Value="false" />
		</Transport>
		<SongMasterValues>
			<SessionScrollerPos X="0" Y="0" />
		</SongMasterValues>
		<SignalModulations />
		<GlobalQuantisation Value="4" />
		<AutoQuantisation Value="0" />
		<Grid>
			<FixedNumerator Value="1" />
			<FixedDenominator Value="16" />
			<GridIntervalPixel Value="20" />
			<Ntoles Value="2" />
			<SnapToGrid Value="true" />
			<Fixed Value="false" />
		</Grid>
		<ScaleInformation>
			<RootNote Value="0" />
			<Name Value="Major" />
		</ScaleInformation>
		<InKey Value="false" />
		<SmpteFormat Value="0" />
		<TimeSelection>
			<AnchorTime Value="0" />
			<OtherTime Value="0" />
		</TimeSelection>
		<SequencerNavigator>
			<BeatTimeHelper>
				<CurrentZoom Value="0.254945054945054927" />
			</BeatTimeHelper>
			<ScrollerPos X="0" Y="0" />
			<ClientSize X="745" Y="490" />
		</SequencerNavigator>
		<IsContentSplitterOpen Value="true" />
		<IsExpressionSplitterOpen Value="true" />
		<ExpressionLanes>
			<ExpressionLane Id="0">
				<Type Value="0" />
				<Size Value="41" />
				<IsMinimized Value="false" />
			</ExpressionLane>
			<ExpressionLane Id="1">
				<Type Value="1" />
				<Size Value="41" />
				<IsMinimized Value="false" />
			</ExpressionLane>
			<ExpressionLane Id="2">
				<Type Value="2" />
				<Size Value="41" />
				<IsMinimized Value="true" />
			</ExpressionLane>
			<ExpressionLane Id="3">
				<Type Value="3" />
				<Size Value="41" />
				<IsMinimized Value="true" />
			</ExpressionLane>
		</ExpressionLanes>
		<ContentLanes>
			<ExpressionLane Id="0">
				<Type Value="4" />
				<Size Value="41" />
				<IsMinimized Value="false" />
			</ExpressionLane>
			<ExpressionLane Id="1">
				<Type Value="5" />
				<Size Value="25" />
				<IsMinimized Value="true" />
			</ExpressionLane>
		</ContentLanes>
		<ViewStateFxSlotCount Value="4" />
		<ViewStateSessionMixerHeight Value="120" />
		<Locators>
			<Locators>@LOCATORS@</Locators>
		</Locators>
		<DetailClipKeyMidis />
		<TracksListWrapper LomId="0" />
		<VisibleTracksListWrapper LomId="0" />
		<ReturnTracksListWrapper LomId="0" />
		<ScenesListWrapper LomId="0" />
		<CuePointsListWrapper LomId="0" />
		<ChooserBar Value="1" />
		<Annotation Value="" />
		<SoloOrPflSavedValue Value="true" />
		<SoloInPlace Value="true" />
		<CrossfadeCurve Value="2" />
		<LatencyCompensation Value="2" />
		<HighlightedTrackIndex Value="0" />
		<GroovePool>
			<LomId Value="0" />
			<Grooves />
		</GroovePool>
		<AutomationMode Value="false" />
		<SnapAutomationToGrid Value="true" />
		<ArrangementOverdub Value="false" />
		<ColorSequenceIndex Value="1276962075" />
		<AutoColorPickerForPlayerAndGroupTracks>
			<NextColorIndex Value="6" />
		</AutoColorPickerForPlayerAndGroupTracks>
		<AutoColorPickerForReturnAndMasterTracks>
			<NextColorIndex Value="15" />
		</AutoColorPickerForReturnAndMasterTracks>
		<ViewData Value="{}" />
		<ResetNonautomatedMidiControllersOnClipStarts Value="true" />
		<MidiFoldIn Value="false" />
		<MidiFoldMode Value="0" />
		<MultiClipFocusMode Value="false" />
		<MultiClipLoopBarHeight Value="0" />
		<MidiPrelisten Value="false" />
		<LinkedTrackGroups />
		<AccidentalSpellingPreference Value="3" />
		<PreferFlatRootNote Value="false" />
		<UseWarperLegacyHiQMode Value="false" />
		<VideoWindowRect Top="-2147483648" Left="-2147483648" Bottom="-2147483648" Right="-2147483648" />
		<ShowVideoWindow Value="true" />
		<TrackHeaderWidth Value="93" />
		<ViewStateArrangerHasDetail Value="true" />
		<ViewStateSessionHasDetail Value="true" />
		<ViewStateDetailIsSample Value="false" />
		<ViewStates>
			<SessionIO Value="1" />
			<SessionSends Value="1" />
			<SessionReturns Value="1" />
			<SessionMixer Value="1" />
			<SessionTrackDelay Value="0" />
			<SessionCrossFade Value="0" />
			<SessionShowOverView Value="0" />
			<ArrangerIO Value="1" />
			<ArrangerReturns Value="1" />
			<ArrangerMixer Value="1" />
			<ArrangerTrackDelay Value="0" />
			<ArrangerShowOverView Value="1" />
		</ViewStates>
	</LiveSet>
</Ableton>
)ALS";
}
}
