#!/usr/bin/env python3
"""Turns a real, Live-saved Live 11.3 set into Source/Engine/AlsTemplate.h.

Every working open-source .als generator starts from a set Live itself saved
and only edits known fields; writing the ~1700-line schema from scratch is
not viable. This script cuts Live11_3_template.xml (Ableton's own near-empty
test set from github.com/Ableton/maxdevtools, MIT - see
LICENSE-Ableton-maxdevtools.txt) into three pieces with @PLACEHOLDER@ tokens
that Source/Engine/AlsWriter.cpp fills in:

  kAlsHead      <?xml ...> ... <Tracks>          @NEXT_POINTEE_ID@
  kAlsMidiTrack one empty MIDI track, cloned per song track:
                @TRACK_ID@ @NAME@ @COLOR@ @ARRANGEMENT_CLIPS@ and @P0@..@Pn@
                for every pointee-pool id (renumbered per clone)
  kAlsTail      </Tracks> ... </Ableton>          @TEMPO@ @LOCATORS@

Usage: python3 Tools/als_template/make_als_template.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "Live11_3_template.xml"
OUT = HERE.parent.parent / "Source" / "Engine" / "AlsTemplate.h"

# Elements in Live's global pointee pool (see AlsWriter.h).
POOL_RE = re.compile(r'(<(?:\w*Target|Pointee|ControllerTargets\.\d+) Id=")(\d+)(")')


def one(pattern, text, repl, count=1):
    new, n = re.subn(pattern, repl, text, count=count)
    assert n == count, f"expected {count} match(es) for {pattern!r}, got {n}"
    return new


def main():
    xml = SRC.read_text()

    head_end = xml.index("<Tracks>") + len("<Tracks>\n")
    track_start = xml.index("\t\t\t<MidiTrack ")
    track_end = xml.index("</MidiTrack>\n") + len("</MidiTrack>\n")
    assert xml[head_end:track_start] == "", "template must contain exactly one track"
    assert xml[track_end:].lstrip().startswith("</Tracks>"), "template must contain exactly one track"

    head = xml[:head_end]
    track = xml[track_start:track_end]
    tail = xml[track_end:]

    head = one(r'<NextPointeeId Value="\d+" />', head, '<NextPointeeId Value="@NEXT_POINTEE_ID@" />')

    # Drop the template's Max for Live device (and its pool ids) - generated
    # tracks carry no devices; the user loads their own instruments.
    track, n = re.subn(r"\n(\t+)<Devices>\n.*?\n\1</Devices>", r"\n\1<Devices />", track, count=1, flags=re.S)
    assert n == 1 and "MxDevice" not in track

    track = one(r'<MidiTrack Id="\d+">', track, '<MidiTrack Id="@TRACK_ID@">')
    track = one(r'<EffectiveName Value="[^"]*" />', track, '<EffectiveName Value="@NAME@" />')
    track = one(r'<UserName Value="[^"]*" />', track, '<UserName Value="@NAME@" />')
    track = one(r'(</Name>\n\t+)<Color Value="\d+" />', track, r'\1<Color Value="@COLOR@" />')
    # The FIRST ArrangerAutomation/Events is MainSequencer's (arrangement
    # clips); the second is FreezeSequencer's and must stay empty.
    track = one(r"(<ArrangerAutomation>\n\t+)<Events />", track, r"\1@ARRANGEMENT_CLIPS@")
    assert "PointeeId" not in track, "track-internal pointee references would need remapping"

    counter = [0]

    def renumber(m):
        k = counter[0]
        counter[0] += 1
        return f"{m.group(1)}@P{k}@{m.group(3)}"

    track = POOL_RE.sub(renumber, track)
    pool_per_track = counter[0]

    tail = one(r'(<Tempo>\n\t+<LomId Value="0" />\n\t+)<Manual Value="[\d.]+" />', tail, r'\1<Manual Value="@TEMPO@" />')
    tail = one(r'(<FloatEvent Id="\d+" Time="-63072000" )Value="[\d.]+"', tail, r'\1Value="@TEMPO@"')
    tail = one(r"<Locators>\n\t+<Locators />\n\t+</Locators>", tail, "<Locators>\n\t\t\t<Locators>@LOCATORS@</Locators>\n\t\t</Locators>")

    rest_ids = [int(m.group(2)) for m in POOL_RE.finditer(head + tail)]
    first_track_pool_id = max(rest_ids) + 1

    for piece in (head, track, tail):
        assert ')ALS"' not in piece

    OUT.write_text(
        "#pragma once\n\n"
        "// GENERATED by Tools/als_template/make_als_template.py - do not edit by hand.\n"
        "//\n"
        "// Derived from a Live Set saved by Ableton Live 11.3.13, from\n"
        "// github.com/Ableton/maxdevtools (maxdiff/tests/test_files/Test Project/Test.als),\n"
        "// Copyright (c) 2024 Ableton AG, MIT License - see\n"
        "// Tools/als_template/LICENSE-Ableton-maxdevtools.txt.\n\n"
        "namespace Engine\n{\nnamespace AlsTemplate\n{\n"
        f"    // Number of @Pk@ pool-id placeholders in kAlsMidiTrack.\n"
        f"    constexpr int kPoolIdsPerTrack = {pool_per_track};\n"
        f"    // First free pool id above everything in kAlsHead/kAlsTail.\n"
        f"    constexpr int kFirstTrackPoolId = {first_track_pool_id};\n\n"
        f'    constexpr const char* kAlsHead = R"ALS({head})ALS";\n\n'
        f'    constexpr const char* kAlsMidiTrack = R"ALS({track})ALS";\n\n'
        f'    constexpr const char* kAlsTail = R"ALS({tail})ALS";\n'
        "}\n}\n"
    )
    print(f"wrote {OUT} (pool ids per track: {pool_per_track}, first track pool id: {first_track_pool_id})")


if __name__ == "__main__":
    main()
