#pragma once
#include <JuceHeader.h>
#include <array>

// AbletonCopilot MIDI — a companion MIDI-effect plugin. Chain it directly
// before an instrument (Serum2, Diva, ...) on a MIDI track and it plays a
// bassline generated by the main AbletonCopilot Drum Machine plugin, kept in
// sync by reading the small pattern file that plugin writes on every edit
// (~/Library/AbletonCopilot/melody_pattern.json) — same handoff idea already
// used between the plugin and the Companion Python script (analysis.json).
//
// Each step in the JSON is either null (no note) or an integer semitone
// offset from the key root — used directly as the played pitch, so whatever
// the Drum Machine's Melody row shows (generated or hand-edited) is exactly
// what comes out here.
class AbletonCopilotMidiAudioProcessor : public juce::AudioProcessor,
                                          private juce::Timer
{
public:
    AbletonCopilotMidiAudioProcessor();
    ~AbletonCopilotMidiAudioProcessor() override;

    void prepareToPlay(double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

   #ifndef JucePlugin_PreferredChannelConfigurations
    bool isBusesLayoutSupported(const BusesLayout& layouts) const override;
   #endif

    void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    const juce::String getName() const override;
    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool isMidiEffect() const override;
    double getTailLengthSeconds() const override;

    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram(int index) override;
    const juce::String getProgramName(int index) override;
    void changeProgramName(int index, const juce::String& newName) override;

    void getStateInformation(juce::MemoryBlock& destData) override;
    void setStateInformation(const void* data, int sizeInBytes) override;

    // --- status, read by the editor for the small status display ---
    std::atomic<bool> patternFileFound { false };
    std::atomic<int>  activeStepCount  { 0 };
    std::atomic<int>  keyRootForUI     { 0 };

    // Drum-pattern status (see below) - separate from the melody status
    // above since they're two independent handoff files.
    std::atomic<bool> drumPatternFileFound  { false };
    std::atomic<int>  drumActiveStepCount   { 0 };

    static constexpr int kNumSteps = 128; // must match DrumMachineComponent::kNumSteps

    // Diagnostics (temporary, added while debugging the drum path end to
    // end) - read by the editor's status display.
    std::atomic<int>  drumPollCount        { 0 }; // increments every timerCallback() tick - proves the timer is alive
    std::atomic<int>  drumNoteOnCount      { 0 }; // increments every drum noteOn emitted in processBlock
    std::atomic<bool> transportPlaying     { false };
    std::atomic<bool> drumRolesParsedOk    { false }; // true once readDrumPatternFile() successfully parsed >=1 role

private:
    void timerCallback() override; // polls the pattern files off the audio thread
    void readMelodyPatternFile();  // extracted so its early-returns can't block readDrumPatternFile() - see below

    juce::File  patternFile;
    juce::int64 lastPatternFileMTime = 0;

    static constexpr int kNoNote = -128;

    juce::CriticalSection       patternLock;
    std::array<int, kNumSteps>  pattern; // guarded by patternLock; kNoNote = no note at this step
    int                         patternKeyRoot = 0;

    // Audio-thread-only playback state (melody voice - single, held-note style)
    int  lastStepIndex   = -1;
    bool noteCurrentlyOn = false;
    int  soundingPitch   = -1;

    // --- Drum pattern (Phase 1 deterministic engine, Source/Engine/) ---
    // Up to 4 independent roles (kick/clap/hat/perc), each a short gated
    // hit rather than the melody voice's held-until-next-event style -
    // real drum hits are short strikes, not sustained notes.
    static constexpr int kMaxDrumRoles = 4;

    struct DrumRoleData
    {
        int                          midiNote = -1; // -1 = unused slot
        std::array<int, kNumSteps>   velocity {};   // 0 = no hit at this step, 1-127 = velocity
    };

    juce::File  drumPatternFile;
    juce::int64 lastDrumPatternFileMTime = 0;

    juce::CriticalSection                          drumPatternLock;
    std::array<DrumRoleData, kMaxDrumRoles>         drumRoles; // guarded by drumPatternLock

    // Audio-thread-only playback state, one gated voice per role slot.
    struct DrumVoiceState
    {
        bool  noteOn          = false;
        int   pitch           = -1;
        int   samplesUntilOff = 0;
    };
    std::array<DrumVoiceState, kMaxDrumRoles> drumVoices;
    int drumLastStepIndex = -1;

    void readDrumPatternFile(); // called from timerCallback()

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(AbletonCopilotMidiAudioProcessor)
};
